services:
    api:
        image: piston:arm64
        platform: linux/arm64
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
